language: go

go:
  - 1.14
  - tip

notifications:
  email: false

env:
  global:
    # Coveralls.io token.
    - secure: "HNrDFePQtzPHSOl1LKTWoeHqPndqB35O0viW"

install:
  - go get -t ./...

before_script:
  - wget https://github.com/mewmew/ci/raw/master/get_tools.sh
  - chmod +x get_tools.sh
  - ./get_tools.sh
  - wget https://github.com/mewmew/ci/raw/master/ci_checks.sh
  - chmod +x ci_checks.sh

script:
  - ./ci_checks.sh
