name: Test Coveralls

on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]
  schedule:
    - cron: "29 21 * * 6"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.x"
          check-latest: true

      - name: normal tests
        run: go test ./...

      - name: race tests
        run: go test -race ./...

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
            github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
            path-to-lcov: ./coverage.out
